#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
killall "picom"
bash "$HOME/.config/wpg/wp_init.sh" &
#killall "deadd-notification-center"
#deadd-notification-center &
wmname LG3D &
#transmission-daemon &
bspc config window_gap          12
bspc config border_width         4
bspc config split_ratio          0.50
bspc config -m eDP-1 top_padding 28
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config -m eDP-1 top_monocle_padding -28

autorandr --change benq 
bspc monitor eDP-1 -d 1 2 3 4 5 
bspc monitor HDMI-1-0 -d 6 7 8 9 0 
xset -dpms s off &
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a discord desktop='^4' follow=off
bspc rule -a Slack desktop='^4' follow=off
bspc rule -a mplayer2 state=floating
bspc rule -a jetbrains-studio state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

#feh --bg-fill ~/.config/awesome/theme/wallpapers/6.png
bash "$HOME/.config/wpg/wp_init.sh" &
picom --experimental-backends &
# source /home/nitish/.config/polybar/forest/launch.sh
killall "polybar"
polybar -q main -c "$HOME/.config/polybar/forest/config.ini" &	
xsetroot -cursor_name left_ptr &
capesc
bspc config focus_follows_pointer true
bspc config border_width 3
# source the colors.
. "${HOME}/.cache/wal/colors.sh"

# Set the border colors.
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"

bspc config presel_feedback_color "$color1"
